### ISSUE TITLE
The .env.production mentions portal name

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileeditor#39]
The `.env.production` is not generic enough as it mentions `OOD_PORTAL`.

**Comment by nickjer** [comment]
Could you explain to me what error shows up if you don't specify the `OOD_DATAROOT` environment variable?

**Comment by nickjer** [comment]
It may be the case that you just need to add an OOD Appkit initializer:

```ruby
# config/initializers/ood_appkit.rb

OodAppkit.configure do |config|
  config.routes.files_rack_app = false
end
```

**Comment by ericfranz** [comment]
When building assets:

```
rake aborted!
OodAppkit::Engine::UndefinedDataroot: OodAppkit.dataroot must be defined (default: ENV['OOD_DATAROOT'])
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/ood_appkit-0.1.0/lib/ood_appkit/engine.rb:21:in `block in <class:Engine>'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/config/environment.rb:5:in `<top (required)>'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/application.rb:189:in `require'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/application.rb:189:in `require_environment!'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/railties-4.0.0/lib/rails/application.rb:249:in `block in run_tasks_blocks'
/users/PZS0645/wiag/ood_portals/ondemand_test/sys/file-editor/vendor/bundle/ruby/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
```

**Comment by nickjer** [comment]
Ah, from here:

https://github.com/OSC/ood_appkit/blob/b91a54d59173f222b6fed1fc30be232c508d50b2/lib/ood_appkit/engine.rb#L21

Maybe this should be removed.

**Comment by brianmcmichael** [comment]
Adding the initializer doesn't resolve the error. We'll have to keep the `OOD_DATAROOT` until the check is removed from OOD Appkit.

**Comment by nickjer** [comment]
Right, that was what @ericfranz pointed out. The error is raised when that variable is not set.

**Comment by brianmcmichael** [comment]
Related: https://github.com/OSC/ood-fileeditor/issues/38

**Comment by ericfranz** [comment]
For the dashboard, I do this: https://github.com/OSC/ood-dashboard/blob/00c17c9af9a55175614df687ff46ff38fc2cb151/.env.production

In .env.production:

```
OOD_PORTAL="ondemand"
```

In .env.local.awesim:

```
OOD_PORTAL="awesim"
```

Ah. The problem here:

```
efranz@webtest04:~/awesim/dev/dashboard (master)$ RAILS_ENV=production bin/rails c
Loading production environment (Rails 4.2.7.1)
=> Unable to load pry
irb(main):001:0> ENV["OOD_DATAROOT"]
=> "/users/PZS0562/efranz/ondemand/data/sys/dashboard"
irb(main):002:0>
irb(main):002:0> ENV["OOD_PORTAL"]
=> "awesim"
```

So the problem with the dashboard AND here is the same - OOD_DATAROOT points to the wrong location, regardless of what OOD_PORTAL is eventually set to.

**Comment by nickjer** [comment]
We shouldn't make `OOD_DATAROOT` a requirement.

**Comment by ericfranz** [comment]
By making it optional we are just pushing the problem off to the future.

**Comment by nickjer** [comment]
How so?

**Comment by brianmcmichael** [comment]
We need to find a way to deal with it for database apps, but I don't think it should be a requirement, especially since we're giving developers the ability to build their own apps in the dashboard, which is where I originally discovered the issue.

OOD_DATAROOT is unnecessary in this app, and it's reasonable to assume that other developers will want to create an app without state. In that case, the burden would be on us to explain `OOD_DATAROOT` and why they need to put it in their app, and I don't think we can justify it.

**Comment by brianmcmichael** [comment]
Added a workaround at c05e8abfeecf0eb13ee02171e4ebed58cd723559 that should be removed if OOD_DATAROOT requirement is removed.

Can anyone see any problems with setting data root to `/dev/null` since it isn't being used anyways?

**Comment by nickjer** [comment]
@brianmcmichael is this fixed?

**Comment by ericfranz** [comment]
Not relevant since converting to Sinatra app, we are no longer using ood_appkit.
